version: v1alpha1
debug: false
persist: true
machine:
    type: controlplane
    token: h442c1.bj67hjpikqnlyu02
    ca:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQekNCOHFBREFnRUNBaEVBOEYyeVRMV0FNOXdMM2pjNkZOb0kzakFGQmdNclpYQXdFREVPTUF3R0ExVUUKQ2hNRmRHRnNiM013SGhjTk1qVXdOakkxTVRBeE9EQXdXaGNOTXpVd05qSXpNVEF4T0RBd1dqQVFNUTR3REFZRApWUVFLRXdWMFlXeHZjekFxTUFVR0F5dGxjQU1oQUoxR3Y2a1RybGJHZ3lWY2ZDSDBUMi9raVh6UWVYZWN5eUh6CjMxV2NyajVXbzJFd1h6QU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUcKQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRklSaUFwRTc4QWFlcUZXWApmaGhpWFVyMi9yZVFNQVVHQXl0bGNBTkJBTjRHNzB3dFZVdVdUODJpRThyY1g5N29YcVdwejBtRVNrSC9Ubzh5CjRJYk1Oa2dwWVZMUlJrYk5vSmNmbWtjRmNSSXMrVWo2RmViQzFQMnZQVUVwdUFFPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: LS0tLS1CRUdJTiBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0KTUM0Q0FRQXdCUVlESzJWd0JDSUVJSFlqdm8wLzFIK1piZDVYVW15YmpyOCtZUElFeFhPcDlYNjFjM3h5WjNoSQotLS0tLUVORCBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0K
    certSANs: []
    kubelet:
        image: ghcr.io/siderolabs/kubelet:v1.33.2
        defaultRuntimeSeccompProfileEnabled: true
        disableManifestsDirectory: true
    network:
        hostname: cp-1
        interfaces:
            - interface: ens18
              addresses:
                - 192.168.23.11/24
              routes:
                - network: 0.0.0.0/0
                  gateway: 192.168.23.1
              dhcp: false
        nameservers:
            - 8.8.8.8
            - 8.8.4.4
    install:
        disk: /dev/sda
        image: factory.talos.dev/metal-installer/956b9107edd250304169d2e7a765cdd4e0c31f9097036e2e113b042e6c01bb98:v1.10.4
        wipe: false
    time:
        servers:
            - 1.ru.pool.ntp.org
            - 2.ru.pool.ntp.org
            - 3.ru.pool.ntp.org
    registries:
        mirrors:
            docker.io:
                endpoints:
                    - https://dockerhub.timeweb.cloud
                    - https://mirror.gcr.io
    features:
        rbac: true
        stableHostname: true
        apidCheckExtKeyUsage: true
        diskQuotaSupport: true
        kubePrism:
            enabled: true
            port: 7445
        hostDNS:
            enabled: true
            forwardKubeDNSToHost: true
    nodeLabels:
        node.kubernetes.io/exclude-from-external-load-balancers: ""
cluster:
    id: UXkozLu4WyAuSbBlqoexvO3BPhYRBBqOvwXGhvQlKmo=
    secret: KRo3CBb17yynWSUXJ351GnSBYYCBEZ2C2XfTRYNKTSA=
    controlPlane:
        endpoint: https://192.168.23.11:6443
    clusterName: talos-demo
    network:
        cni:
            name: none
        dnsDomain: cluster.local
        podSubnets:
            - 10.244.0.0/16
        serviceSubnets:
            - 10.96.0.0/12
    token: nz9295.nfwxy0zr3mqtxgcv
    secretboxEncryptionSecret: kfpDxegspGHe10W+lbSZ7Ql05zK50DBl9kZhELYQC9M=
    ca:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpVENDQVRDZ0F3SUJBZ0lSQU5RME00VjhlczJDV3d2bEhxdkRaQlF3Q2dZSUtvWkl6ajBFQXdJd0ZURVQKTUJFR0ExVUVDaE1LYTNWaVpYSnVaWFJsY3pBZUZ3MHlOVEEyTWpVeE1ERTRNREJhRncwek5UQTJNak14TURFNApNREJhTUJVeEV6QVJCZ05WQkFvVENtdDFZbVZ5Ym1WMFpYTXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CCkJ3TkNBQVRkSzlvSGpscjJ4Nk8xUDlQVGVGNG9oRG9ma05xcGo1ZUc2MmdiVVBEN1lhNU1pL1UvczJrd3JpSnkKWmhqTlNHZ00yek95ak9KUjljMFdQd0VScDZtd28yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FvUXdIUVlEVlIwbApCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPCkJCWUVGQmNFTGVHRzFWTk8xNVJOS3B0Skg3SUlaUkhoTUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUJySm9IdWoKT1F2Z1V2YjJKWDhZL3FnRkJHU0F3dEx2bXJwZktSMVhHcFlBQWlBMHpMcEFua2pjZG04Z1h4dVVEaERINXlYQwpzUzdXNTdULzdPNThMSUUyRHc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUNoQWZxRFhQUXNqS0xvQzB1TEZ5bitML2pKaytOSTA0SXZOU2lRTnVZUkFvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFM1N2YUI0NWE5c2VqdFQvVDAzaGVLSVE2SDVEYXFZK1hodXRvRzFEdysyR3VUSXYxUDdOcApNSzRpY21ZWXpVaG9ETnN6c296aVVmWE5GajhCRWFlcHNBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
    aggregatorCA:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJYekNDQVFhZ0F3SUJBZ0lSQUs5bnpmREdzOXU3MzBycEhYd1pIVEF3Q2dZSUtvWkl6ajBFQXdJd0FEQWUKRncweU5UQTJNalV4TURFNE1EQmFGdzB6TlRBMk1qTXhNREU0TURCYU1BQXdXVEFUQmdjcWhrak9QUUlCQmdncQpoa2pPUFFNQkJ3TkNBQVF2QUdYekoySDRUc3FKYWJPYkRsWHh6K1hxdkw0M1ExR1hLUWxlV0x2YnlFZTB0azZnClV0MWVDRjZLd1AvKzcxbGcyVHBmRXV4b0J6SW0zVlMwck5icm8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FvUXcKSFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpIUVlEVlIwT0JCWUVGQWRHSUxmZWlFQWI0Njg4VktUZWZJOXBMMlY4TUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDCklET3RsRXlsNTBDYi9GbE45UlcxNFcrakNGRkduRHhGNDY3bGRqQnh5WjRJQWlCak1hdWxqOGovM3ZIN05Bc1IKS1JHRkFXdkdacGZ2VFdzbWtQMWxVOGRDZ3c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSVBSNnR5aVluZFl2MGdRc09xSnRma2RZdzV3NXh6dnQ0UkV6RDIvTE1pUjZvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFTHdCbDh5ZGgrRTdLaVdtem13NVY4Yy9sNnJ5K04wTlJseWtKWGxpNzI4aEh0TFpPb0ZMZApYZ2hlaXNELy91OVpZTms2WHhMc2FBY3lKdDFVdEt6VzZ3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
    serviceAccount:
        key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS0FJQkFBS0NBZ0VBNHIvdHY0WXpFVU96ZmFUc0pyQytjaUc0dTQyNVA5a3dKelZnc0VPSUlRVGppYVZRCjJsWFRFRWpjTHJTYjhKNlJJdXZmSXQ0dDdXVFExVmZKMUIxVktPT1N5SVJ6MFpGVUwvalNQMjM3elhCb1RISEEKQTNqWlg0anlBVHpFMkhkZGNvand6OFovbTFiNVZ1OWFiNzZFODlWSjZMREU0NnYybnljK2o2eFBIVVJWanRicAprT21rRmRRVzh6TW5qM2c3d1dkUkxCTUluT00reU8vekRDN3oxY0d5aTU0Z0JvMVBUUmtzVU8yM1M4bjhZeThrCjh3c2swcDBjM3hJd0MzT2VRVHkvY1pEOVFrMkR4LzlJYWo0ZElyMERJekF5TlIrTCtpR1pnOGFlYzY3YmgvbDEKVFpTaHYxY3pTdzJEVkpCLzlxZ01XY2IxV1ZCR2JVSVoxdC9XYUc5SWJTNlhuNlFLTUlkd1R4Mlp3Z2FEd1htNwpBalV2MGlpWnpKTW5hcU8rd2xGdS9hRTArYXlsMkxKN1J6Tmk1cnd0VnVSVko1S2NwOTRZV25EY3NHRUFxTlRzCjRPMWJBZXcvcmVsdFRDZkZGUVB5NjMvRWZGY3FENnd6SzRwS2lQMVpqcWc2Q1ZHNXlONndtMTFzeEFJN3gzSGkKS1B5NGNhMTYybDlkYWp4QWJuYjgrSk4vVE9HR3hqcUY0Q1FBSUE0REJyQlZOelJrUDkyTUdsOFlSQzMzVEZDYgpSVGZYRlVhcnRzeEZUZDVsVHIxUWorcnUyRmFNYWdKZmFJUzB0Z1NDdlR1OW9FNE80a1ZYVTNIbGxLaEVEczRPCkhjc0lJR0k5ZFpoNkFIQU1BSlhZNldEenJQRHNOblYyZWs5T01PRlgzZWhLSWxyb1k1czJ0cEVaZjlzQ0F3RUEKQVFLQ0FnQWJQNHd1OVU0Q3Q1dUVzRUp1bmRPcy9HOXFIbXhTQjJQNWVqa2R4V2ZBN0FqNTNBTmMwVzUxS1FSSQptb3lZdkQxZHNIR1dpNU9DVVJpbFlwRE83QjExTmUvSUo5NlJJd0UyYUpTL2FaU1dTZmxHb202OEhCUW5IbHBTCm1yNWU4dTBvVzl0d1pINm1LS3Y2N2ZWMHN6VGY1bFFrNGNVdlJOVjBwNjhsYmNQdUZPMmhKaU5ZTmpOeEtoVDkKOGJwQnkrV0dac2VDMytDcmxjVlFPVUdBUjg0bWRFbmo3RU1WOW5vK25oVk12bHhGLzhaVUZ2QytRaXNSSWk4NwpnVUNEeDhlUE9HRWJJUnpHRUhHVElaTE9yWnNydHdIL0F3WXRpeFp6bndFSExHR1RMa0tVVXY1dExieklOUTdsCmFJRE5NellsYW1sZGlvS21VbmE4SDNMaWR2Q1pUMENjN1l4b0Q4eEE5L2RiRTIyUGM2ekw5OEdybDFkNzVyS2kKWUpjVml1TGM0Qm1ueTVrNUZhcm84VVVsbC95N3luRlI5dld1VDdRbHVSeC9odjVJM21hM1dLYThxa04yZ0tabwpnREFMM3RZK29NZE5PQ0tQcGtvdWhRa1pQcDgrUWtWemNheEhlVmh6T0l3T3o1TkxvR0lSakNvUFc1VWlRNzhJCng0cEtzcUN5blZuR3FSUmN2R1N3anlxREtTdjk2NTBzMlVERHN6cXFvT0tuSzVsWThBdlhZdDZCRkVRTVZvMFQKS2xBNW93emxBYW1ZTm9HR0Z6V1pUTEI3WWhKUnRaZHU1TmR2SmoyT3R6d29md28rUnFLRjJlRmtOSHpSVG9PUgp4S0NWSmE5c2lkb2ZHY2FPVkNJNE1xTjlhMUkrMldSMEF2Qk1iZ2Rpb1o0NkFjelk0UUtDQVFFQStjd21DNU95CmtvaUlzQXFicEl2WGtKSTBYK3FrVzBtMWxLRUZYNU13Q1grdXVxT3pQU0wyZkVLMGh2UkZ4VElWUVJuNys3MDcKK2VlRE5tVnNwcGwrU3Z6ME1zWUFYVzRzWnRtYzc2ZHlLdUNONERoUy9JbUt6cjFscWZwYm5tM3pVK2w3UjR1SwpxWnFXMHlwa1RkZnVOaHdKS2xMWXNzVjQ0azJCTlJIV0gvbzI3MXREQVU1dldxRmJKUWdEZEFoSWhtaEtGWlZlCkVjQVJMMnY3UzhMaU1WVlBvalJKbGRMcW1VQXhVRVpzSUVOaCtYaU9CQjUvZVp3dlZqcE05VjJkajJ1dnkrMWEKZ1JJSTB6SVpHUm9nS1ZhZWV4cjYvRHZRWHJWS3dPby9TcmVVY0VDMHVqRitHbW9Xa3RjcHdhOXBMK3dmZk9iUQpUR2NLb3lhWlpCWjgrd0tDQVFFQTZHRkdvTEE4Y09yTnIvVUVvWHk3ZDBDQTJDbnhCV2ZSaEJ1VzZCNHQ5VzJ1CmNyNThsb1RWWUNONWx2Q3JuRTVPN25PYnByTUZlWldsdWp5QlprZlE0eXdxMkdiR0FVQ3d5U2o3bmI5SWozVTYKbW81dnhNREN5MWZoL2pRZlN5TURNSjkyVm5ldllRU0ozQmJTYzJ0eTEvdDREeXpGZDhoY2t3ZWYyTWpRNGY2aApqL2tWcmVyckwvWXROclhYd2JwRjFiN1Y4ZldBS3IxWXRXWEx3VGtlSW1FWFhKclUzR0Jkd2RZbVlEVG9mclpvCjYxbjBKZnM0SHo2RThHSEM0ZFZqVWtGZ0o4RHVJSENXaGVXWEZHVUV6MEdNVkxyTTdtU2dJVWRmdlN2dnIzNWgKV0k3OTVncllzUEk1L2ZoTUwvTC9TalIwVjVUeDdSaGhnRzRBekIzU29RS0NBUUJNYjlHOGZTZUplMG9JUkZhNApGU3FUVEluR1IvQ2ZGb0QveC8zeTd3RW1Cdklhbm5qOFhqUjZkWmIwTE04a3RseVduVExrSjFXdzlNekwybUZTCjRXa3AzUm1FWjk0NHVMdlJoUWxtdENCVlNuMWZmUnkzdGdiSm1GOEJrbUJ5ckVabkNPejJTWmJXcXowM3hLTUkKeHVoWG1tQ2JtTnBDYWZiQm1PSE9zWFNLT0hDUzhhUWhSRFVDMEprcFRiaHd5eEFXUU5kYW4yZzNta1FuOUt6aQowL0dQRXdIWktwTFJ5OGFKdW9EY2haQVVsMG5sb3FRaVVvckRWYTJPZnl5SmNHb0VOdm1HTjAwWWJjSlJqZVRzCkwzaGo3ZU4wM0I2dERFaUlrb1ViWHhLYTlHM3hvM3NwOW5jVjhoeVNObERLdWJoQU44cXkxNVlwcXVZd1ltRlIKcFNmOUFvSUJBUUNEZDQweW1hSUlLLzdrSGxWWld5emY0YUZES2k5T1pKYlhDNWpMaDA5dSszZG5PVGRaSEp0dgpBWUxuanc4M3BlSG42NFhTd0pOSFh3OWNscUNLa2ZTdW9TMDRNcVN3enIxMWdQY2hIcmZaV1hRblBwQWpHdjdaCmRjWElRQXE0UW4ycWczeTZuSW1lOUtkZDJaZUVidlNSRnBhczF5SjhpdUU4MldKb2pld0cvenkrTENoRXRaUUwKRlZZdERxR2EyMXhvK2NjbVZVTUdhd3NGelNxQ0RXTnNCY3ZtdXozVDA3MFhUYVYyWmxobVg2SnFEQUVoZjhnWApmUkpPd0xBMWZianNMMHBNRTAxbEV1MUZvVWRnNVduY0szUk45MFM3VmpoMXUyQ0JzSnF3aVdwZlpMNWw2QnNCCnVIaHdvNG5PMHNYMVlFbTF4dkU3dHNCcW5WRmNLVDhoQW9JQkFCSWl1anZRWW1NR2hOM2lzSktRbGRORWpWN04KbEFVaVBJbGNvRndsd3YxMnhqZE5pNDBWNFlIVmcvN094ekJuT3FEM0dBMGpWZE9QK1dnV3pQOGpReTg3M0JjMQovUWd3RGhHM2NwWkJXSmpwY2xuZW9MSy80V0VSUVh0VUd4RDFWUEtEVnZpeDNtSUVPSk5ER0ladWZOMWtVRDhKCnJtUXhJSTJIVnpNOWJ6dE1HeGRneEhPbTFOYWZUcFhEY3dGRXJBTW1Ba3l1NFZFOGJoV0ZKcElZblk1NTRoZjkKb0doMEQxaFhySWlTY2YrR00wdlRMaGwyZ1JPS0VjaXJ3KzVRanVuN0I2M0pCOVgzaStuSXdlb3Y0Q2o2YVNMegpkTFlyQ2ZVblk4bmErZDhaMjNsRDUxZU1BTTZocjhkeDNwb0l0YnFQUmlaOHJlNWhPWW8vR0xZd1REND0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K
    apiServer:
        image: registry.k8s.io/kube-apiserver:v1.33.2
        certSANs:
            - 192.168.23.11
        disablePodSecurityPolicy: true
        admissionControl:
            - name: PodSecurity
              configuration:
                apiVersion: pod-security.admission.config.k8s.io/v1alpha1
                defaults:
                    audit: restricted
                    audit-version: latest
                    enforce: baseline
                    enforce-version: latest
                    warn: restricted
                    warn-version: latest
                exemptions:
                    namespaces:
                        - kube-system
                    runtimeClasses: []
                    usernames: []
                kind: PodSecurityConfiguration
        auditPolicy:
            apiVersion: audit.k8s.io/v1
            kind: Policy
            rules:
                - level: Metadata
    controllerManager:
        image: registry.k8s.io/kube-controller-manager:v1.33.2
    proxy:
        disabled: true
        image: registry.k8s.io/kube-proxy:v1.33.2
    scheduler:
        image: registry.k8s.io/kube-scheduler:v1.33.2
    discovery:
        enabled: true
        registries:
            kubernetes:
                disabled: true
            service: {}
    etcd:
        ca:
            crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJmakNDQVNTZ0F3SUJBZ0lSQU5ERTFoMmxKTkIrbVBsUXE0UC9NS2d3Q2dZSUtvWkl6ajBFQXdJd0R6RU4KTUFzR0ExVUVDaE1FWlhSalpEQWVGdzB5TlRBMk1qVXhNREU0TURCYUZ3MHpOVEEyTWpNeE1ERTRNREJhTUE4eApEVEFMQmdOVkJBb1RCR1YwWTJRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFSVnlURGdYNk5DCmFSMlNjcndDU1FXWTVubmwyQndFc3QrbzFVNzdxZ0t1S0IwQk1yZkhjL1VDVTFNMlFoUDk5SzdpWjM0ZjJiY1EKNkhNdlpoalFuLzBubzJFd1h6QU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSApBd0VHQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkM4MGZuWnpRbTZrCnA2TWg0RlRZQXd4MENnTE5NQW9HQ0NxR1NNNDlCQU1DQTBnQU1FVUNJRk1xWkVMY2JNMGdwMDBYQ2c1U1RtZHoKYzNNVTFpeFhYVjJGN0MxR3RLdURBaUVBMFhiMHhGb2c0OXRXeG5NOTQ5S2JFZWtwdkpkQ0ppZHlaeDU1RldHTgpoekE9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
            key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUdiclNqcUptY0t0cXdDeHRMN09wZytFcU5pS2pqQ1d2VGsxdm95YXd0YmhvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFVmNrdzRGK2pRbWtka25LOEFra0ZtT1o1NWRnY0JMTGZxTlZPKzZvQ3JpZ2RBVEszeDNQMQpBbE5UTmtJVC9mU3U0bWQrSDltM0VPaHpMMllZMEovOUp3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
