version: v1alpha1
debug: false
persist: true
machine:
    type: worker
    token: h442c1.bj67hjpikqnlyu02
    ca:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQekNCOHFBREFnRUNBaEVBOEYyeVRMV0FNOXdMM2pjNkZOb0kzakFGQmdNclpYQXdFREVPTUF3R0ExVUUKQ2hNRmRHRnNiM013SGhjTk1qVXdOakkxTVRBeE9EQXdXaGNOTXpVd05qSXpNVEF4T0RBd1dqQVFNUTR3REFZRApWUVFLRXdWMFlXeHZjekFxTUFVR0F5dGxjQU1oQUoxR3Y2a1RybGJHZ3lWY2ZDSDBUMi9raVh6UWVYZWN5eUh6CjMxV2NyajVXbzJFd1h6QU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUcKQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRklSaUFwRTc4QWFlcUZXWApmaGhpWFVyMi9yZVFNQVVHQXl0bGNBTkJBTjRHNzB3dFZVdVdUODJpRThyY1g5N29YcVdwejBtRVNrSC9Ubzh5CjRJYk1Oa2dwWVZMUlJrYk5vSmNmbWtjRmNSSXMrVWo2RmViQzFQMnZQVUVwdUFFPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: ""
    certSANs: []
    kubelet:
        image: ghcr.io/siderolabs/kubelet:v1.33.2
        defaultRuntimeSeccompProfileEnabled: true
        disableManifestsDirectory: true
    network:
        hostname: worker-1
        interfaces:
            - deviceSelector:
                physical: true
              addresses:
                - 192.168.23.12/24
              routes:
                - network: 0.0.0.0/0
                  gateway: 192.168.23.1
              dhcp: false
        nameservers:
            - 8.8.8.8
            - 8.8.4.4
    install:
        disk: /dev/sda
        image: factory.talos.dev/metal-installer/956b9107edd250304169d2e7a765cdd4e0c31f9097036e2e113b042e6c01bb98:v1.10.4
        wipe: false
    time:
        servers:
            - 1.ru.pool.ntp.org
            - 2.ru.pool.ntp.org
            - 3.ru.pool.ntp.org
    registries:
        mirrors:
            docker.io:
                endpoints:
                    - https://dockerhub.timeweb.cloud
                    - https://mirror.gcr.io
    features:
        rbac: true
        stableHostname: true
        apidCheckExtKeyUsage: true
        diskQuotaSupport: true
        kubePrism:
            enabled: true
            port: 7445
        hostDNS:
            enabled: true
            forwardKubeDNSToHost: true
    kernel:
        modules:
            - name: drbd
              parameters:
                - usermode_helper=disabled
            - name: drbd_transport_tcp
            - name: dm-thin-pool
cluster:
    id: UXkozLu4WyAuSbBlqoexvO3BPhYRBBqOvwXGhvQlKmo=
    secret: KRo3CBb17yynWSUXJ351GnSBYYCBEZ2C2XfTRYNKTSA=
    controlPlane:
        endpoint: https://192.168.23.11:6443
    clusterName: talos-demo
    network:
        cni:
            name: none
        dnsDomain: cluster.local
        podSubnets:
            - 10.244.0.0/16
        serviceSubnets:
            - 10.96.0.0/12
    token: nz9295.nfwxy0zr3mqtxgcv
    ca:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpVENDQVRDZ0F3SUJBZ0lSQU5RME00VjhlczJDV3d2bEhxdkRaQlF3Q2dZSUtvWkl6ajBFQXdJd0ZURVQKTUJFR0ExVUVDaE1LYTNWaVpYSnVaWFJsY3pBZUZ3MHlOVEEyTWpVeE1ERTRNREJhRncwek5UQTJNak14TURFNApNREJhTUJVeEV6QVJCZ05WQkFvVENtdDFZbVZ5Ym1WMFpYTXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CCkJ3TkNBQVRkSzlvSGpscjJ4Nk8xUDlQVGVGNG9oRG9ma05xcGo1ZUc2MmdiVVBEN1lhNU1pL1UvczJrd3JpSnkKWmhqTlNHZ00yek95ak9KUjljMFdQd0VScDZtd28yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FvUXdIUVlEVlIwbApCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPCkJCWUVGQmNFTGVHRzFWTk8xNVJOS3B0Skg3SUlaUkhoTUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUJySm9IdWoKT1F2Z1V2YjJKWDhZL3FnRkJHU0F3dEx2bXJwZktSMVhHcFlBQWlBMHpMcEFua2pjZG04Z1h4dVVEaERINXlYQwpzUzdXNTdULzdPNThMSUUyRHc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: ""
    proxy:
        disabled: true
    discovery:
        enabled: true
        registries:
            kubernetes:
                disabled: true
            service: {}
